### ISSUE TITLE
Build error when using isomorphic-dompurify in angular 15 universal

### ISSUE THREAD

**Issue by praveshShetty** [kkomelin/isomorphic-dompurify#203]
I'm trying to use isomorphic dompurify's sanitize function, in my angular application, which uses angular universal for server side rendering. While there is no error when running the application as a client side rendered one. server side rendering is not working.

<img width="1195" alt="Screenshot 2023-07-01 at 2 53 51 PM" src="https://github.com/kkomelin/isomorphic-dompurify/assets/128784467/c7c08367-063e-4b83-96a0-6079632d1d56">

Is this a known issue.

I'm currently using 

"angular" : 15.2.2
"typescript": "4.9.4"
"node" : 16.19.1
"isomorphic-dompurify": "^1.7.0"

**Comment by kkomelin** [comment]
Hi @praveshShetty,

Thanks for reporting the issue.

Unfortunately, the log doesn't say a lot. Could you please provide a sandbox project where I could reproduce the issue?

**Comment by kkomelin** [comment]
What is your hosting environment?

**Comment by JeremyGuinn** [comment]
@kkomelin, I'm also seeing this error, but I have a bit more info relating to it.

```
./node_modules/jsdom/lib/jsdom/living/generated/utils.js:34
const AsyncIteratorPrototype = Object.getPrototypeOf(Object.getPrototypeOf(async function* () {}).prototype);
                                      ^


TypeError: Cannot convert undefined or null to object
    at Function.getPrototypeOf (<anonymous>)
    at Object.39178 (./node_modules/jsdom/lib/jsdom/living/generated/utils.js:34:39)
    at __webpack_require__ (./webpack/bootstrap:19:1)
    at Object.96057 (./node_modules/jsdom/lib/api.js:11:18)
    at __webpack_require__ (./webpack/bootstrap:19:1)
    at <anonymous> (./node_modules/isomorphic-dompurify/index.js:1:196)
    at Object.64682 (./node_modules/isomorphic-dompurify/index.js:1:262)
    at __webpack_require__ (./webpack/bootstrap:19:1)
    at Module.682 (./src/app/core/services/footer.service.ts:7:21)
    at __webpack_require__ (./webpack/bootstrap:19:1)

Node.js v18.12.1
```

I'll update this comment with a minimal reproduction.

**Comment by kkomelin** [comment]
Thanks @JeremyGuinn for the information. 
Please also take a look at the other jsdom related issue https://github.com/kkomelin/isomorphic-dompurify/issues/54 , if folks suggested a solution which can help you.

**Comment by JeremyGuinn** [comment]
Here is a [codesandbox ](https://codesandbox.io/p/sandbox/isomorphic-dompurify-issue-replication-m584z4?file=%2Fsrc%2Fapp%2Fapp.component.ts%3A3%2C1-4%2C1) that gets the same error when running dev:ssr

**Comment by kkomelin** [comment]
Thanks @JeremyGuinn,
From what I can see, the reason is the same as here https://github.com/kkomelin/isomorphic-dompurify/issues/54:
> Warning: Module not found: Error: Can't resolve 'canvas' in '/workspace/node_modules/isomorphic-dompurify/node_modules/jsdom/lib/jsdom'

**Comment by JeremyGuinn** [comment]
Yeah, I'm able to resolve this by using [@angular-builders/custom-webpack](https://www.npmjs.com/package/@angular-builders/custom-webpack).

`angular.json`
```json
{
  ...
  "architect": {
    "build": {
      "builder": "@angular-builders/custom-webpack:browser",
      "options": {
        "customWebpackConfig": {
          "path": "./webpack.config.js"
        },
        ...
      },
      ...
    },
    ...
    "server": {
      "builder": "@angular-builders/custom-webpack:server",
      "options": {
        "customWebpackConfig": {
          "path": "./webpack.config.js"
        },
        ...
      },
      ...
    },
    ...
  },
  ...
}
```

`webpack.config.js`
```js
module.exports = function(config) {
  return {
    ...config,
    externals: {
      ...config.externals,
      canvas: 'commonjs canvas',
      jsdom: 'commonjs jsdom'
    }
}
```
